# Generated by Django 5.1.5 on 2025-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_fooditem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(upload_to='users/foodimages'),
        ),
    ]
