# Generated by Django 5.1.5 on 2025-04-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'tax'},
        ),
    ]
