# Generated by Django 5.1.5 on 2025-01-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile2',
        ),
    ]
