# Generated by Django 5.1.5 on 2025-01-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_profile_profile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile2',
            name='bg_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/bg_pics'),
        ),
    ]
