# Generated by Django 5.1.5 on 2025-03-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_profile2_bg_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile2',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='address_line2',
        ),
    ]
