# Generated by Django 5.1.5 on 2025-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_rename_address_line1_profile2_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile2',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
