# Generated by Django 5.1.5 on 2025-03-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_profile2_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile2',
            options={'verbose_name': 'profile2', 'verbose_name_plural': 'profiles'},
        ),
    ]
