# Generated by Django 5.1.5 on 2025-04-07 19:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_profile2_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile2',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
